# Generated by Django 4.2.9 on 2024-01-04 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OmeroUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "omero_password",
                    models.CharField(
                        help_text="The password for the omero user", max_length=2000
                    ),
                ),
                (
                    "omero_username",
                    models.CharField(
                        help_text="The username for the omero user", max_length=2000
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that created the dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omero_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
